description: This is a template researchers can walk away with and create their own Portfolio.
datelastupdated: 25 Nov 2021
fullnameofperson: Audrey Zheng
selfIdentification: Urban planner
colour1: "#84A59D"  # sidebar background 
colour2: "#F7EDE2"  # colour of name and desc
colour3: "#F7EDE2"  # colour of Menu links
colour4: "#F5CAC3" # trying to be background colour - still experimenting 
colour5: "#F6BD60“ # menu link colour when hover
